### ISSUE TITLE
Character Roster Crash

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1109]
### Environment
Chummer Version: 5.184.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Chummer starts

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Create a character without a Name, Alias, or Player Name (Unsure which)
Save this character
Close chummer
Open chummer

**Comment by Maxis010** [comment]
System.Xml.XmlException: Data at the root level is invalid. Line 5427, position 13.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Chummer.frmCharacterRoster.CacheCharacter(String strFile) in C:\Coding\chummer5a\Chummer\frmCharacterRoster.cs:line 98
   at Chummer.frmCharacterRoster.LoadCharacters() in C:\Coding\chummer5a\Chummer\frmCharacterRoster.cs:line 70
   at Chummer.frmCharacterRoster..ctor() in C:\Coding\chummer5a\Chummer\frmCharacterRoster.cs:line 18
   at Chummer.frmMain..ctor() in C:\Coding\chummer5a\Chummer\frmMain.cs:line 136
   at Chummer.Program.Main() in C:\Coding\chummer5a\Chummer\Program.cs:line 97

**Comment by chummer5a** [comment]
Hrm. Any chance you could upload the character file? Compressing it to a zip will let you upload it here.

**Comment by Maxis010** [comment]
I fixed the old file by editing through notepad, I'll experiment with new characters see if I can find the precise breaking value and upload it

**Comment by Maxis010** [comment]
And now I can't recreate the issue

Complete steps taken to create the crash
- Character made on machine 1
- Uploaded to a Teamspeak via it's filetransfer system to a Windows server
- Downloaded (same method) to machine 2
- Machine 2 crash on attempting to open the file

Issue resolved by
- Editing the file via Notepad to include an alias, name and playername on Machine 3 (mine)

Issue resolved on machine 2 by
- Using the new file made on machine 3
- Deleting chummer5 from the registry

The machine 1 is having issues opening some of our other characters so I'm going to go poke around there
