### ISSUE TITLE
Issue adding limited version of alter memory spell

### ISSUE THREAD

**Issue by Nuclearstorm** [chummer5a/chummer5a#1120]
### Environment
Chummer Version: 5.184.10.0
Environment: Windows 10
Runtime: unknown

### Expected behaviour
able to add alter memory as a limited spell both at character creation and during play

### Actual behaviour
when attempting to add alter memory as a limited spell, chummer crashes

### Steps to reproduce the behaviour
attempt to add alter memory as a limited spell at any time

### Link to affected character file
any attempted character file is affected

**Comment by chummer5a** [comment]
Hrm, I can't replicate the issue. Do you get the same crash selecting Astral Armour?

**Comment by Nuclearstorm** [comment]
I do not get the same crash selecting astral armor, only alter memory as a limited spell in my experience. It seems to happen no matter the variables (before/after chargen, races, mage/mystic adept, karma/sumto10, etc.) 

    On Tuesday, September 27, 2016 8:24 AM, Chummer 5 Is Alive <notifications@github.com> wrote:
 

 Hrm, I can't replicate the issue. Do you get the same crash selecting Astral Armour?—

**Comment by chummer5a** [comment]
Could you enable Debug Logging in the Options menu and try it again? There should be a chummerlog.txt file in the application folder once you've started using Chummer with that enabled; if you could try again and send me the resulting log file, I might be able to get something more promising.

**Comment by Nuclearstorm** [comment]
Alright for this log all I did was make a new character, add magician, and attempt to add alter memory as a limited spell 

    On Monday, October 3, 2016 10:14 AM, Chummer 5 Is Alive <notifications@github.com> wrote:
 

 Could you enable Debug Logging in the Options menu and try it again? There should be a chummerlog.txt file in the application folder once you've started using Chummer with that enabled; if you could try again and send me the resulting log file, I might be able to get something more promising.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   
Info      Program.cs.Main:68 Application Chummer5a build 5.184.10.0 started at 10/3/2016 7:25:14 PM with command line arguments "C:\Users\William\Desktop\Shadowrun 5\Chummer.Nightly (2)\Chummer5.exe" 
Info      clsTimekeeper.cs.Finish:67 Task "cache_load" finished in 00:00:00.0786266
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectBuildMethod..ctor(Character objCharacter, Boolean blnUseCurrentValues) in C:\projects\chummer5a\Chummer\Character Creation\frmSelectBuildMethod.cs:line 91
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectBuildMethod..ctor(Character objCharacter, Boolean blnUseCurrentValues) in C:\projects\chummer5a\Chummer\Character Creation\frmSelectBuildMethod.cs:line 91
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectBuildMethod..ctor(Character objCharacter, Boolean blnUseCurrentValues) in C:\projects\chummer5a\Chummer\Character Creation\frmSelectBuildMethod.cs:line 91
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 515
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 515
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.lstMetatypes_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 349
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.lstMetatypes_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 349
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 515
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 515
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.lstMetatypes_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 349
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.lstMetatypes_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 349
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 515
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmKarmaMetatype.lstMetatypes_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmKarmaMetatype.cs:line 349
Entering clsImprovement.cs.CreateImprovements:899 CreateImprovements
Info      clsImprovement.cs.CreateImprovements:900 objImprovementSource = Metatype
Info      clsImprovement.cs.CreateImprovements:901 strSourceName = Elf
Info      clsImprovement.cs.CreateImprovements:902 nodBonus = <bonus />
Info      clsImprovement.cs.CreateImprovements:903 blnConcatSelectedValue = False
Info      clsImprovement.cs.CreateImprovements:904 intRating = 1
Info      clsImprovement.cs.CreateImprovements:905 strFriendlyName = Elf
Info      clsImprovement.cs.CreateImprovements:906 intRating = 1
Info      clsImprovement.cs.CreateImprovements:926 _strForcedValue = 
Info      clsImprovement.cs.CreateImprovements:928 _strLimitSelection = 
Info      clsImprovement.cs.CreateImprovements:962 Calling Commit
Entering clsImprovement.cs.Commit:2003 Commit
Exiting   clsImprovement.cs.Commit:2008 Commit
Info      clsImprovement.cs.CreateImprovements:964 Returned from Commit
Exiting   clsImprovement.cs.CreateImprovements:979 CreateImprovements
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, Boolean blnCreateChildren) in C:\projects\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 112
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, Boolean blnCreateChildren) in C:\projects\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 133
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, Boolean blnCreateChildren) in C:\projects\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 171
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, Boolean blnCreateChildren) in C:\projects\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 178
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
First chance exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "movement" of type "System.String" in System.String.Character
Entering clsImprovement.cs.RemoveImprovements:1039 RemoveImprovements
Info      clsImprovement.cs.RemoveImprovements:1040 objImprovementSource = ArmorEncumbrance
Info      clsImprovement.cs.RemoveImprovements:1041 strSourceName = Armor Encumbrance
Exiting   clsImprovement.cs.RemoveImprovements:1919 RemoveImprovements
Entering clsImprovement.cs.RemoveImprovements:1039 RemoveImprovements
Info

**Comment by chummer5a** [comment]
Unfortunately that's not a super helpful error. Could you please try again with Nightly-v5.185.26? 

If the crash still happens, it should bump you into the crash handler. Click on the 'What does this error contain' link and it should open a folder with your error details. Open up the exception.txt file and paste what you find in there.
