### ISSUE TITLE
Chummer crashes when creating a spirit.

### ISSUE THREAD

**Issue by pknull** [chummer5a/chummer5a#1225]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.187.0
Environment: Windows 10
Runtime: .NET
Report was
dff184de-f034-4051-9438-4807fb8933cd

### Expected behaviour
I try to create a Guardian Spirit character. OR, if there's an issue with an XML file or such, maybe a pointer to correct it.

### Actual behaviour
Chummer crashes, giving an error of a value being set to 0.

### Steps to reproduce the behaviour
File.New Critter
Select 'Spirits'
Select a spirit type, give it a force and click OK

### Link to affected character file
None due to crash

**Comment by chummer5a** [comment]
Thaaaat's interesting. You're not supposed to be able to access that segment of code, we block it away behind a requirement for Running Wild. Do you have a custom book enabled or something?

**Comment by pknull** [comment]
I do :/ So we shouldn't be trying to create critters or? I grabbed the running wild book and stuck it in with some other customer books for some custom mentors... (custom custom custom)

I assumed the issue was because of the custom, but the error is very vague :(

**Comment by pknull** [comment]
I've included my files here. Please don't hate me too much, just trying to figure out what I did wrong.

[data.zip](https://github.com/chummer5a/chummer5a/files/596366/data.zip)

**Comment by chummer5a** [comment]
Well, the mentors in your mentors file there should have GUIDs populated to prevent weird stuff from happening, which you can use https://www.guidgenerator.com for. I can't actually replicate the crash with the spirits though. When it crashed, it should have opened a crash report window. Can you click the blue link on that window and copy the contents of the exception.txt file?

**Comment by pknull** [comment]
```
System.ArgumentOutOfRangeException: Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected() in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 13898
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 570
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by chummer5a** [comment]
Aha. Okay, I see the problem. Technically easyfix, but I may as well manage some other stuff with spirits while I'm at it. Will be fixed soonish.

**Comment by pknull** [comment]
Thanks, let me know if there's anything I can do to help, etc.
