### ISSUE TITLE
Chummer crashes on startup

### ISSUE THREAD

**Issue by twtse** [chummer5a/chummer5a#1275]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.188.3 and Nightly-v5.188.46
Environment: Windows 10
Runtime: http://puu.sh/sFMWH/415769c706.png

### Expected behaviour
Chummer should execute and open

### Actual behaviour
Chummer immediately crashes upon execution

### Steps to reproduce the behaviour
Deleting chummer files, re-downloading files, trying both stable and nightly versions

### Link to affected character file
N/A

**Comment by chummer5a** [comment]
Please try updating to .Net 4.5.2 or later. https://www.microsoft.com/en-au/download/details.aspx?id=42642

**Comment by twtse** [comment]
I launched the .exe file from that link and got:
http://puu.sh/sFNqU/17ce0a0d2c.png

**Comment by chummer5a** [comment]
Hmmmm. It might be munging the character roster on load. When it crashes, it should open a window that prompts you to send us an error log. There should be a blue link on that window; if you click that, it'll open an explorer window that has an exception.txt file. Can you open that file and post the contents?

**Comment by twtse** [comment]
Thanks for the quick responses by the way! That's very interesting. I went ahead and re-created the directory that it was searching for and now the application launches without crashing. For future reference, is there a way to change the path? The contents of the exception.txt file are as follows:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Truman\Desktop\Etc\D&D\Shadowrun\Chummer5.184.0'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Chummer.frmCharacterRoster.LoadCharacters() in C:\projects\chummer5a\Chummer\frmCharacterRoster.cs:line 77
   at Chummer.frmCharacterRoster..ctor() in C:\projects\chummer5a\Chummer\frmCharacterRoster.cs:line 21
   at Chummer.frmMain..ctor() in C:\projects\chummer5a\Chummer\frmMain.cs:line 144
   at Chummer.Program.Main() in C:\projects\chummer5a\Chummer\Program.cs:line 97

**Comment by chummer5a** [comment]
The character roster just reads your recent file history and pulls the character  in from that. I'll fix the code so it doesn't fail so explosively.

**Comment by chummer5a** [comment]
Actually out of curiousity, how much of the path did you have to rebuild? I still can't get it to crash in my test environment with missing folder paths

**Comment by twtse** [comment]
Just the last directory; that was the only one missing.

**Comment by twtse** [comment]
To be precise: it started crashing when I was trying to make a new character with the directory missing. That's when I tried deleting all the files and re-downloading everything. From there, it would crash upon starting.

**Comment by chummer5a** [comment]
Thaaaaaat's interesting. So can you replicate the crash, or the process flow? Like Chummer starts without crashing, create a character, save a character, close Chummer, delete folder, launch Chummer, crash?

**Comment by twtse** [comment]
I was able to replicate the crashing by creating a new directory, setting the character roster file to that directory, closing chummer, deleting the directory, and then launching directory. Here's the contents of the exception text file if you're interested:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Truman\Desktop\Etc\D&D\Shadowrun\Test'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Chummer.frmCharacterRoster.LoadCharacters() in C:\projects\chummer5a\Chummer\frmCharacterRoster.cs:line 77
   at Chummer.frmCharacterRoster..ctor() in C:\projects\chummer5a\Chummer\frmCharacterRoster.cs:line 21
   at Chummer.frmMain..ctor() in C:\projects\chummer5a\Chummer\frmMain.cs:line 144
   at Chummer.Program.Main() in C:\projects\chummer5a\Chummer\Program.cs:line 97

**Comment by chummer5a** [comment]
Ahhhhh, the character roster's what killed it! Okay, easyfix. Thanks for the help

**Comment by twtse** [comment]
No problem! Glad I could be of help. Thanks for being so responsive.
