### ISSUE TITLE
Issue with Loading and Making New Character with already 7 characters

### ISSUE THREAD

**Issue by malakeyegod** [chummer5a/chummer5a#1285]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version:  5.188.3
Environment: (Windows 10)
Runtime: ( .NET 4.5.1)

### Expected behaviour
(To be able to make characters past 7)

### Actual behaviour
(Program crashes after Chose Character Priories page. This happen if I try the Karma page as well. Crash Reporter pops up every time. )

### Steps to reproduce the behaviour
(Tried every kind of build but this continues to happen)

### Link to affected character file
()

**Comment by chummer5a** [comment]
The Crash Reporter has a blue link that points to the exceptions file. Can you open exception.txt and paste the contents?

**Comment by malakeyegod** [comment]
Yea, sure. I'll be on if you need me.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmPriorityMetatype.MetatypeSelected() in C:\projects\chummer5a\Chummer\Character Creation\frmPriorityMetatype.cs:line 981
   at Chummer.frmPriorityMetatype.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmPriorityMetatype.cs:line 541
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at Chummer.frmMain.ShowNewForm(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\frmMain.cs:line 620
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in C:\projects\chummer5a\Chummer\Program.cs:line 98

**Comment by chummer5a** [comment]
Looks like it can't find your selected metatype.  What'd you pick?

**Comment by malakeyegod** [comment]
I tried all to see if it was just one or two. That one was dwarf.

**Comment by chummer5a** [comment]
Hrm. Please try updating to the latest nightly build via https://github.com/chummer5a/chummer5a/releases/download/Nightly-v5.188.57/Chummer.Nightly.zip.

**Comment by malakeyegod** [comment]
That fixed it.
