### ISSUE TITLE
5.189.6 - Crashing when choosing the SKILLS tab

### ISSUE THREAD

**Issue by jthibs** [chummer5a/chummer5a#1321]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.189.6
Environment: (Operating system here. If it persists over multiple OS's list them all) Win 10 Anniversary
Runtime: (If you don't know this, it is probably .NET 4.5.1) Net 4.5.1

### Expected behaviour
Expectation to click on the skills tab to load up skills. 

### Actual behaviour
Crashes program. 

### Steps to reproduce the behaviour
Opening new or existing character built with any method of building. The unit will crash when clicking on the skills tab. All other tabs work correctly. Issue started after the program was updated to the 5.189.6

### Link to affected character file
n/a

**Comment by chummer5a** [comment]
Hrm, I can't replicate it. when the application crashes, you should see a blue link that opens a folder in your temp directory. Can you open up the exception.txt file in that folder and post the contents?

**Comment by jthibs** [comment]
Happy Holiday, 

Here is your requested information. 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Chummer.LanguageManager.GetString(String strKey)
   at Chummer.UI.Skills.SkillsTabUserControl.GenerateDropdownFilter()
   at Chummer.UI.Skills.SkillsTabUserControl.RealLoad()
   at Chummer.UI.Skills.SkillsTabUserControl.SkillsTabUserControl_Load(Object sender, EventArgs e)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabPage.set_Visible(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jthibs** [comment]
oops! reopened with contents, sorry about that! Too much eggnog.

**Comment by chummer5a** [comment]
Hrm. The crash is because it can't find a string that's required in the dropdown filter. Normally that would indicate that you've got the wrong version of the file; does it persist if you download Chummer from scratch and overwrite?

**Comment by jthibs** [comment]
Let me uninstall and reinstall as a clean update. I have not tried with a clean install - only updating through the updater option. 

FYI: Sorry for the slowness in responding, Holiday and all of that.

**Comment by jthibs** [comment]
New install - issue resolved. Thanks for the assistance!
