### ISSUE TITLE
Chummer crashes when clicking on print (to view charactersheet/print it to pdf)

### ISSUE THREAD

**Issue by Dreyven** [chummer5a/chummer5a#1353]
[exception.txt](https://github.com/chummer5a/chummer5a/files/720132/exception.txt)
[attributes.txt](https://github.com/chummer5a/chummer5a/files/720133/attributes.txt)

### Environment
Chummer Version: 5.189.48.0
Environment: Windows 10 and 7

### Expected behaviour
Clicking on Print causes some sort of interface to open where you can select things and eventually print a charactersheet.

### Actual behaviour
Clicking on Print crashes chummer.

### Steps to reproduce the behaviour
Click on Print

### Link to affected character file
https://drive.google.com/open?id=0B3qNr4n5M8jtdTcyRVRZcENHTkU

**Comment by chummer5a** [comment]
Could you please try downloading the latest build manually? There seems to be an issue for some people where the DLLs don't copy over. Otherwise, could you show me the error message in the crash handler window?

**Comment by Dreyven** [comment]
Emptied chummer folder completely and replaced everything, didn't help.

![grafik](https://cloud.githubusercontent.com/assets/24802412/22173068/19148734-dfb8-11e6-85cf-7986f433162c.png)

**Comment by chummer5a** [comment]
Well that's annoying. Can you click the blue link and paste the contents of the exception.txt file that opens up?

Also, can you give me a screenshot of your Chummer folder?

**Comment by Dreyven** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24802412/22175411/6307fbaa-dff4-11e6-902d-d0624ec076b5.png)

The exception.txt is already attached to my post at the very top but i guess i can.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Print(XmlTextWriter objWriter) in C:\projects\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 602
   at Chummer.Character.PrintToStream(MemoryStream objStream, XmlTextWriter objWriter) in C:\projects\chummer5a\Chummer\Classes\clsCharacter.cs:line 2496
   at Chummer.Character.Print(Boolean blnDialog) in C:\projects\chummer5a\Chummer\Classes\clsCharacter.cs:line 2653
   at Chummer.frmCreate.tsbPrint_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 1942
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in C:\projects\chummer5a\Chummer\Program.cs:line 98

**Comment by chummer5a** [comment]
Ack, sorry about that. I had it in my head that it was a different issue and didn't properly read what was going on. The problem is that the Riot Shield is expecting to find an Exotic Melee Weapons skill to base it's rating off, but crashes because it can't find it. If you add the skill it'll stop crashing. You don't need to invest any karma in it, just need to be able to fetch the name.

**Comment by Dreyven** [comment]
That did do it. Although you DO have to invest karma, at least when you are no longer in character creation.
