### ISSUE TITLE
 Issue: Switching skill and magic priority crashes Chummer

### ISSUE THREAD

**Issue by jessicalevine** [chummer5a/chummer5a#1418]
### Environment
Crash ID: 1b0146b7-564d-4d38-9540-d704c0611af3
Chummer Version: 5.190.65
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour
Change priority selection of skills from D to C and magic from C to D, and gain the increased skill points and decreased magic rating.

### Actual behaviour
Immediate crash.

### Steps to reproduce the behaviour
1. Load the attached .chum5
2. Go to "Change Priority Selection"
3. Switch the priority of skills and magic
4. Click "OK'

https://www.dropbox.com/s/ludcf1harmqjpx9/Jack.bak.chum5?dl=0

**Comment by jessicalevine** [comment]
crash reporting is also crashing, but here is the error ![screenshot 2017-02-09 11 41 52](https://cloud.githubusercontent.com/assets/321230/22793107/e1b770c6-eebc-11e6-8baa-9d5498a00ce4.png)

**Comment by jessicalevine** [comment]
Exception file contents:
```
System.ArgumentOutOfRangeException: Value of '-1' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.ChangeMetatype() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 20752
   at Chummer.frmCreate.mnuSpecialChangeMetatype_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 1972
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in C:\projects\chummer5a\Chummer\Program.cs:line 101
```

**Comment by chummer5a** [comment]
Can't access the dropbox file, can you zip and upload it here?

**Comment by DelnarErsike** [comment]
Could you check again with the latest nightly build?
