### ISSUE TITLE
 Issue: - Chummer Crashing on opening of character file

### ISSUE THREAD

**Issue by galvorbak99** [chummer5a/chummer5a#1424]
### Environment
Crash ID: bf458d7d-2820-4717-9864-e4f226ae0edd
Chummer Version: 5.190.74
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Character file will open as normal

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
1. Open a character file
2. The program will crash

**Comment by chummer5a** [comment]
What's the error message say? Can you upload your character file?

**Comment by galvorbak99** [comment]
![capture1](https://cloud.githubusercontent.com/assets/20749593/22859886/1fabc716-f0a1-11e6-9fec-bbbe99a36875.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20749593/22859892/410bc262-f0a1-11e6-8ced-fefedd928f54.PNG)

**Comment by chummer5a** [comment]
Well, it's trying to load one of your attributes but for some reason the minimum is higher than 1. Can you click the blue link and paste the contents of the exception.txt file that should appear in the folder?

**Comment by galvorbak99** [comment]
System.ArgumentOutOfRangeException: Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 13503
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 606
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Right, AI Depth. Figured it might be that. Assuming the character isn't an AI, we just need to blat everything back down to zero. Open the character file up in notepad and find the DEP attribute node. Should be around line 230, you can find it by looking for <name>DEP</name>.

Replace that with 

`		<attribute>
			<name>DEP</name>
			<metatypemin>0</metatypemin>
			<metatypemax>0</metatypemax>
			<metatypeaugmax>0</metatypeaugmax>
			<value>0</value>
			<base>0</base>
			<karma>0</karma>
			<augmodifier>0</augmodifier>
			<totalvalue>0</totalvalue>
		</attribute>`

**Comment by galvorbak99** [comment]
I cannot find DEP anywhere in the character file

**Comment by chummer5a** [comment]
Ha! Well that's definitely the problem then. Just add that node at the end of the attributes block. It should wind up looking like this:

![image](https://cloud.githubusercontent.com/assets/11448441/22870358/94b0ac0c-f1fa-11e6-849e-ac7db96ae2bc.png)

**Comment by galvorbak99** [comment]
That seems to have cleared things up. Thanks
