### ISSUE TITLE
 Issue: - OPening character file chummer crashes

### ISSUE THREAD

**Issue by flamingcarebear** [chummer5a/chummer5a#1512]
### Environment
Crash ID: 37a8e0c6-9520-4ef6-ab16-2afbacca59eb
Chummer Version: 5.191.27
Environment: Windows 8.1
Runtime: 4.0.30319.34209

### Expected behaviour
Open File

### Actual behaviour
CHummer Crash

### Steps to reproduce the behaviour
Open File

Exception.txt
System.ArgumentOutOfRangeException: Value of '12' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.ContactControl.set_ConnectionRating(Int32 value)
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by flamingcarebear** [comment]
Issue corrected, one of the contacts connection rating was set at 12 instead of 6.
Friends in high places allows for the increase, but also resets the value to 6 once removed, in addition that quality was not used on this character.
