### ISSUE TITLE
Unhandled Exception when loading a character with Friends in High Places Quality

### ISSUE THREAD

**Issue by BodieSullivan** [chummer5a/chummer5a#156]
When a character is in create mode and they have Friends in High Places, they get contacts with greater than 6 connection. The character was created on an older version that didn't limit the connection rating to 6. When it is loaded up now, an unhandled exception is thrown.

There should be a check to see if the character has the Friends in HIgh Places quality before hardcoding the maximum value of the numeric spinner to 6.

Changing line 44 of ContactControl.cs to be the following should resolve the issue:
```
if (!_objCharacter.Created && !_objCharacter.Qualities.Exists(q => q.Name == "Friends in High Places"))
```

Here is the stack trace:
System.ArgumentOutOfRangeException: Value of '8' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.ContactControl.set_ConnectionRating(Int32 value)
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Fixed in 5.163 with a relatively expensive method in preparation for handling Friends in High Places properly.
