### ISSUE TITLE
Root element is missing?

### ISSUE THREAD

**Issue by AmaneBranwen** [chummer5a/chummer5a#1601]
### Environment
Chummer Version: Every version I've tried: Latest is 5.192.0 - latest Nightly, as well.
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Chummer starts up with no issues.

### Actual behaviour
I get an error that essentially tells me: "Root Element is Missing"

### Steps to reproduce the behaviour
Just attempting to open the chummer.exe executable causes this.

### Link to affected character file
All character files are affected.

Error Message:

---------------------------

---------------------------
Failed to create crash report.
Here is some information to help the developers figure out why
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Users\gfire\AppData\Local\Chummer_for_4th_edition_b\Chummer5.exe_Url_w0cjjza01ikuz24vstyrz1nltw3qmgsw\5.192.0.0\user.config) ---> System.Xml.XmlException: Root element is missing.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()

   at System.Xml.XmlTextReaderImpl.Read()

   at System.Xml.XmlTextReader.Read()

   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)

   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)

   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)

   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()

   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationManager.PrepareConfigSystem()

   at System.Configuration.ConfigurationManager.GetSection(String sectionName)

   at System.Web.Configuration.ClientRuntimeConfig.GetSectionObject(String sectionName)

   at System.Web.Configuration.RuntimeConfig.GetSection(String sectionName, Type type, ResultsIndex index)

   at System.Web.Configuration.RuntimeConfig.get_HttpRuntime()

   at System.Web.Util.HttpEncoder.GetCustomEncoderFromConfig()

   at System.Lazy`1.CreateValue()

   at System.Lazy`1.LazyInitValue()

   at System.Lazy`1.get_Value()

   at System.Web.Util.HttpEncoder.get_Current()

   at System.Web.HttpUtility.JavaScriptStringEncode(String value, Boolean addDoubleQuotes)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeString(String input, StringBuilder sb)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeCustomObject(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeValueInternal(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeValue(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember)

   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat)

   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat)

   at Chummer.Backend.Debugging.CrashHandler.DumpData.SerializeBase64() in D:\Coding\chummer5a\Chummer\Backend\Debugging\CrashHandler.cs:line 95

   at Chummer.Backend.Debugging.CrashHandler.WebMiniDumpHandler(Exception ex) in D:\Coding\chummer5a\Chummer\Backend\Debugging\CrashHandler.cs:line 118
Crash information:
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Users\gfire\AppData\Local\Chummer_for_4th_edition_b\Chummer5.exe_Url_w0cjjza01ikuz24vstyrz1nltw3qmgsw\5.192.0.0\user.config) ---> System.Xml.XmlException: Root element is missing.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()

   at System.Xml.XmlTextReaderImpl.Read()

   at System.Xml.XmlTextReader.Read()

   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)

   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)

   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)

   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()

   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)

   --- End of inner exception stack trace ---

   at System.Configuration.ConfigurationManager.PrepareConfigSystem()

   at System.Configuration.ConfigurationManager.GetSection(String sectionName)

   at System.Web.Configuration.ClientRuntimeConfig.GetSectionObject(String sectionName)

   at System.Web.Configuration.RuntimeConfig.GetSection(String sectionName, Type type, ResultsIndex index)

   at System.Web.Configuration.RuntimeConfig.get_HttpRuntime()

   at System.Web.Util.HttpEncoder.GetCustomEncoderFromConfig()

   at System.Lazy`1.CreateValue()

   at System.Lazy`1.LazyInitValue()

   at System.Lazy`1.get_Value()

   at System.Web.Util.HttpEncoder.get_Current()

   at System.Web.HttpUtility.JavaScriptStringEncode(String value, Boolean addDoubleQuotes)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeString(String input, StringBuilder sb)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeCustomObject(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeValueInternal(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember)

   at System.Web.Script.Serialization.JavaScriptSerializer.SerializeValue(Object o, StringBuilder sb, Int32 depth, Hashtable objectsInUse, SerializationFormat serializationFormat, MemberInfo currentMember)

   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat)

   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat)

   at Chummer.Backend.Debugging.CrashHandler.DumpData.SerializeBase64() in D:\Coding\chummer5a\Chummer\Backend\Debugging\CrashHandler.cs:line 95

   at Chummer.Backend.Debugging.CrashHandler.WebMiniDumpHandler(Exception ex) in D:\Coding\chummer5a\Chummer\Backend\Debugging\CrashHandler.cs:line 118
---------------------------
OK   
---------------------------

**Comment by AmaneBranwen** [comment]
Deleting the MRU keys didn't work whatsoever, either.

**Comment by chummer5a** [comment]
Failed to read root element means that it's trying and failing to parse an XML file, but it's supposed to fail out early if it can't read the file. Um. Do you have a watch folder set up that it might be looking at? Could you try deleting your settings file?

**Comment by AmaneBranwen** [comment]
Where could I find that?

**Comment by chummer5a** [comment]
Should be in the settings folder of wherever you extracted Chummer to.

**Comment by AmaneBranwen** [comment]
My settings folder for Chummer is empty....

**Comment by chummer5a** [comment]
Well, there's definitely something weird going on then. So you extract Chummer into the same or a new folder, try to run the application from that folder, and it gives you the XML error?

**Comment by AmaneBranwen** [comment]
Yes. When it first started, I updated Chummer, thinking it may have just been a file that got moved forward an update, then it started up again with that error. After that, all I needed to do was replace the Chummer.exe to get it to work again - now nothing I try works.

**Comment by AmaneBranwen** [comment]
This is honestly vexing because I finally have a character close to completion to participate in a Shadowrun community, only for this to happen.

**Comment by AmaneBranwen** [comment]
Alright, so the default.xml just appeared. What do I do?

**Comment by AmaneBranwen** [comment]
I figured it out. I had Chummer 5.160.0 extracted onto my computer's hard drive without realizing it. Fixed it, Chummer runs now.
