### ISSUE TITLE
Karma Build Mystic Adept/mystic adept crash

### ISSUE THREAD

**Issue by br3wm45t3r** [chummer5a/chummer5a#165]
Here are the steps:
1. select karma build
2. apply either adept quality to any metatype
3. try and add any negative quality

Then you get a crash with this message:
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectQuality.RequirementMet(XmlNode objXmlQuality, Boolean blnShowMessage) in m:\Coding\chummer5a\Chummer\frmSelectQuality.cs:line 657
   at Chummer.frmSelectQuality.BuildQualityList() in m:\Coding\chummer5a\Chummer\frmSelectQuality.cs:line 351
   at Chummer.frmSelectQuality.cboCategory_SelectedIndexChanged(Object sender, EventArgs e) in m:\Coding\chummer5a\Chummer\frmSelectQuality.cs:line 91
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This does NOT happen when you apply the magician quality though!

**Comment by chummer5a** [comment]
The spectre of blind (Mage) rises once again! Pesky logic fails.

**Comment by br3wm45t3r** [comment]
any thoughts on a quick fix?

**Comment by chummer5a** [comment]
Give yourself the Astral Perception adept power, or just click Continue.
The crash is just an unhandled null exception because you don't have the
appropriate power to grant access to the quality.

**Comment by br3wm45t3r** [comment]
Yup that addresses it.

The only problem is if you don't want the astral perception. Then you are unable to access any negative qualities.

**Comment by br3wm45t3r** [comment]
Thank you by the way

**Comment by chummer5a** [comment]
I'll sort it out this evening for a new build. Shouldn't take much to fix.

**Comment by chummer5a** [comment]
Resolved in 5.164.
