### ISSUE TITLE
Adding Bound spirit during character creation creates exception (.164 I belive)

### ISSUE THREAD

**Issue by Neocyberman** [chummer5a/chummer5a#179]
Working with a mage here. I think it might be that he's psionic tradition.

Improvement idea, larger error window so the entirety of the window can be seen.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.SpiritControl.RebuildSpiritList(String strTradition) in m:\Coding\chummer5a\Chummer\Controls\SpiritControl.cs:line 442
   at Chummer.frmCreate.cmdAddSpirit_Click(Object sender, EventArgs e) in m:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 5586
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Neocyberman** [comment]
Confirmed, it is linked to psionic tradition. Possibly something to do with it not being properly listed what spirit types it uses in the program.

Remains in 165

**Comment by Neocyberman** [comment]
Found the root of the issue I think, none of them have GUI ID's

**Comment by chummer5a** [comment]
Issue is due to 'Spirit of Task' and 'Spirit of Guidance' not being a thing. Yay for data validation. Fixed to Task Spirit and Guidance Spirit in 5.166.
