### ISSUE TITLE
Character file created in 193.174 no longer opens in .179 or .180

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#1819]
[Lumens.zip](https://github.com/chummer5a/chummer5a/files/1166434/Lumens.zip)

### Environment
Crash ID: 41aaeaf3-5d6d-4717-a56c-6c6c71290356
Chummer Version: 5.193.180
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Opening file works

### Actual behaviour
Opening file causes crash

### Steps to reproduce the behaviour
Open Lumens file: https://www.dropbox.com/sh/urt1cky26p0zfbc/AABaUn8Elvh6D5tXbvPmA63va?dl=0

Character was created in earlier version of chummer. Will not open in .179 or .180.

Lumens was created using LifeModules.
Nocturna: Trans-Aleut
Isolated Rural. Test Subject (Bioware), Skipped F/Ed, Terrorist

**Comment by SeanPGorman** [comment]
I am getting no error files here and seeing no errors. Visual Studio debugger is saying:
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in System.Windows.Forms.dll

Additional information: Value of '3' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.

**Comment by SeanPGorman** [comment]
When the crash happens I am seeing a dialog that says; 
System.ArgumentException: Process with an Id of -26948 is not running
at System.Diagnostics.Process.GetProcessbyId(Int32 processId, String machineName)
at System.Diagnostics.Process.GetProcessbyId(Int32 processId)at CrashHandler.CrashDumper.WorkerEntryPoint() in C:\projects\chummer\CrashHandler\CrashDumper.cs:line 126

It seems to be the thing that is preventing the error log?
