### ISSUE TITLE
Chummer crashes when enabling "Allow Adepts to Purchase Power Points during Career" house rule

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2530]
### Environment
Chummer Version: 5.198.17
Environment: Windows 10 (64bit)
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Clicking OK on the dialogue box asking if I want to restart Chummer to apply the changes in the Options panel results in chummer restarting

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Change options, click ok, click ok when it asks if it should restart chummer to apply changes. 

Just looking at the crash file, and it has the following lines near the start:

    System.NullReferenceException: Object reference not set to an instance of an object.
    at Chummer.CharacterOptions.set_MysAdeptAllowPPCareer(Boolean value) in C:\projects\chummer\Chummer\Classes\CharacterOptions.cs:line 1143
    at Chummer.frmOptions.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer\Chummer\frmOptions.cs:line 184

And as best I can tell, the place it is point to  'C:\projects\' doesn't exist. There's no folder by that name on C:

[chummer_crash_131641726968353704.txt](https://github.com/chummer5a/chummer5a/files/1761064/chummer_crash_131641726968353704.txt)

**Comment by Zitchas** [comment]
Follow up:

When I Just select new books then hit OK to close the option box, and accept the option to restart, it restarts cleanly and the books are now selected.

When I go into the House Rules and check a bunch of boxes and then hit ok to close, and then to restart, it crashed again.

Detailed message is: "Object reference not set to an instance of an object."
[chummer_crash_131641737355161635.txt](https://github.com/chummer5a/chummer5a/files/1761078/chummer_crash_131641737355161635.txt)

**Comment by Zitchas** [comment]
I think I've got it narrowed down to the "Allow Mystic Adepts to buy power points during career" option. 

I just checked all the house rules I like, hit ok to close, ok to restart, everything works great, and the options were set. 

I go in again, and check just that one box next to  "Allow Mystic Adepts to buy power points during career" and then it cashes after hitting the two "ok"s.
