### ISSUE TITLE
Character file not opening.

### ISSUE THREAD

**Issue by GreatGodfatherGazoo** [chummer5a/chummer5a#2628]
Character file not opening. 

System.Xml.XmlException: Root element is missing.
at System.Xml.XmlReadershipImpl.Throw(Exception e)
at System.Xml.XmlReadershipImpl.ParseDocumentContext()
at System.Xml.XmlReadershipImpl.Read()
at System.Xml.XmlLoader.Load (Xml Document doc, XmlReader reader, Boolean preserveWhitespace)
at System.Xml.XmlDocument.Load(XmlReader reader)
at System.Xml.XmlDocument.Load(TextReader txtReader)
at Chummer.frmCharacterRoster.CacheCharacter(String strFile) in M:\coding\chummer5\Chummer\frmCharacterRoster.cs:line 45

### Environment
Chummer Version: Chummer 5.198.0
Environment: Windows 10
Runtime: .NET 4.5.1 (Probably)

### Expected behaviour
File should open.

### Actual behaviour
File not opening.

### Steps to reproduce the behaviour
Not sure.

### Link to affected character file
https://drive.google.com/open?id=1C_Q1zkdXf8PwaxRKRj17zMOuqFdWEFmh

**Comment by chummer5a** [comment]
File's busted.

**Comment by GreatGodfatherGazoo** [comment]
No fixing it then?

**Comment by chummer5a** [comment]
Afraid not, you'd have to rewrite from any backups you might have. Check saves\autosaves folder, it might have kept a good copy.

Sent from my Windows 10 phone

**Comment by GreatGodfatherGazoo** [comment]
Found a backup in autosaves. It wasn't entirely up to date, but just needed a few changes to fix that.

**Comment by chummer5a** [comment]
Sorry it broke, I'll see about implementing some thing to validate whether the file has saved properly.

Sent from my Windows 10 phone
