### ISSUE TITLE
 Issue: - Crash on Enemy Addition

### ISSUE THREAD

**Issue by Shadowclaimer** [chummer5a/chummer5a#2938]
### Environment
Crash ID: be1f4860-4252-4ad1-bd67-67dcccd5e271
Chummer Version: 5.202.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Should've adjusted the Connections/Loyalty of an enemy

### Actual behaviour
Warned about max negative karma then crashed

### Steps to reproduce the behaviour
Added an enemy, clicked up or down on the loyalty/connections on them while having 24 negative karma.

**Comment by Shadowclaimer** [comment]
I think this is the one.. I've got a few crash files.

This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it
System.ArgumentOutOfRangeException: Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.ComponentModel.ReflectPropertyDescriptor.SetValue(Object component, Object value)
   at System.Windows.Forms.Binding.SetPropValue(Object value)
   at System.Windows.Forms.Binding.PushData(Boolean force)
   at System.Windows.Forms.BindingManagerBase.PushData(Boolean& success)
   at System.Windows.Forms.PropertyManager.OnCurrentChanged(EventArgs ea)
   at System.Windows.Forms.BindToObject.PropValueChanged(Object sender, EventArgs e)
   at System.ComponentModel.PropertyDescriptor.OnValueChanged(Object component, EventArgs e)
   at System.ComponentModel.ReflectPropertyDescriptor.OnValueChanged(Object component, EventArgs e)
   at System.ComponentModel.ReflectPropertyDescriptor.OnINotifyPropertyChanged(Object component, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Chummer.Contact.OnMultiplePropertyChanged(String[] lstPropertyNames) in M:\Coding\chummer5a\Chummer\Backend\Uniques\Contact.cs:line 126
   at Chummer.Contact.OnPropertyChanged(String strPropertyName) in M:\Coding\chummer5a\Chummer\Backend\Uniques\Contact.cs:line 89
   at Chummer.Contact.set_Loyalty(Int32 value) in M:\Coding\chummer5a\Chummer\Backend\Uniques\Contact.cs:line 490
   at Chummer.CharacterShared.EnemyChanged(Object sender, TextEventArgs e) in M:\Coding\chummer5a\Chummer\Backend\Shared Methods\CharacterShared.cs:line 6589
   at Chummer.ContactControl.nudLoyalty_ValueChanged(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\Controls\ContactControl.cs:line 116
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at System.Windows.Forms.NumericUpDown.UpButton()
   at System.Windows.Forms.UpDownBase.OnUpDown(Object source, UpDownEventArgs e)
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnUpDown(UpDownEventArgs upevent)
   at System.Windows.Forms.UpDownBase.UpDownButtons.BeginButtonPress(MouseEventArgs e)
   at System.Windows.Forms.UpDownBase.UpDownButtons.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in M:\Coding\chummer5a\Chummer\Program.cs:line 113
Crash id is b121a018-4dc8-44f9-988c-1fca6ee8b56b
Crash working directory is C:\Users\asmith1\AppData\Local\Temp\chummer_crash_131794364207473360

**Comment by Shadowclaimer** [comment]
I do only have the Core Rulebook as my only sourcebook if that matters.

**Comment by chummer5a** [comment]
Hrm. The only thing I can think of is you have some kind of contact that comes from an improvement type, but that shouldn't work like that and I can't reproduce it; I think I'll need to see the character file. If you compress it into a zip file you'll be able to upload it here, or you can send it to chummer5isalive@gmail.com.

**Comment by Shadowclaimer** [comment]
[Shigeru Mitani.zip](https://github.com/chummer5a/chummer5a/files/2323997/Shigeru.Mitani.zip)

You'll receive a warning about Run Faster being used (because I added a PACK which isn't in core, but all the gear was core.)

Add an enemy, click down on connections (as if to 0 rating) then back up, and the crash happens to me.

**Comment by chummer5a** [comment]
Latest commit should fix this. Respond if it doesn't and I'll have another look, but I still can't reproduce the error.

**Comment by Shadowclaimer** [comment]
Thank you, highly appreciate this program and everything you do with it. It makes life so much easier and saves me hours every Shadowrun game.
