### ISSUE TITLE
Exception on priority reselection w/ magic and cyberware

### ISSUE THREAD

**Issue by mymsy** [chummer5a/chummer5a#303]
If you give a character cyberware then re-select priorities giving a magic stat greater than their essence supports, chummer will throw an exception. Expected behaviour would be to give magic equal to their essence rounded down.

Steps to reproduce:
1. Create a character with Magic 6 (The 11 bug is showing up here, but it doesn't matter for this demonstration)
2. Add a piece of cyberware. If you go back to the 'Common' tab, Magic will have been adjusted appropriately
3. Special -> Change Priority Selection, and again select something with Magic 6
4. Upon clicking 'Okay' the following exception is thrown

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '5' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.ChangeMetatype()
   at Chummer.frmCreate.mnuSpecialChangeMetatype_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by joha4270** [comment]
Atleast easish to fix. Unless something strange appears expect a fix in 172
