### ISSUE TITLE
Crash on character file load

### ISSUE THREAD

**Issue by Johnny8-0** [chummer5a/chummer5a#3050]
**Describe the bug**
Updated from v2.00.2 to v202.0 and upon loading my character the program crashes.

**To Reproduce**
1. Go to '...' open file
2. Click on '....' my attached character
3. Scroll down to '....' see crash report

**Expected behavior**
Load character

**Screenshots**
![image](https://user-images.githubusercontent.com/29793408/46020331-6b48b580-c0de-11e8-9aa9-51537c80b95b.png)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it
System.ArgumentOutOfRangeException: Value of '1' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.UI.Table.SpinnerTableCell`1.UpdateValue(Object newValue) in M:\Coding\chummer5a\Chummer\UI\Table\SpinnerTableCell.cs:line 59
   at Chummer.UI.Table.TableView`1.UpdateCell(TableColumn`1 column, TableCell cell, T item) in M:\Coding\chummer5a\Chummer\UI\Table\TableView.cs:line 272
   at Chummer.UI.Table.TableView`1.set_Items(BindingList`1 value) in M:\Coding\chummer5a\Chummer\UI\Table\TableView.cs:line 609
   at Chummer.UI.Powers.PowersTabUserControl.RealLoad() in M:\Coding\chummer5a\Chummer\UI\Powers\PowersTabUserControl.cs:line 125
   at Chummer.frmCareer.frmCareer_Load(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\frmCareer.cs:line 539
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Crash id is cad97e6a-f3ca-4ee3-a2db-81f77e2b00bd
Crash working directory is C:\Users\Bruger\AppData\Local\Temp\chummer_crash_131823584206801875

[Johnny8-0.zip](https://github.com/chummer5a/chummer5a/files/2415576/Johnny8-0.zip)

**Comment by chummer5a** [comment]
I believe this is fixed in current nightlies.
