### ISSUE TITLE
Crash on restarting for new version

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#3398]
### Environment
Crash ID: c729bc87-f89a-4505-b256-4a75fccf393e
Chummer Version: 5.203.150
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Restart for new version from dialog

### Actual behaviour
crash
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The process cannot access the file 'C:\Chummer5\chummerprofile' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Chummer.frmUpdate.InstallUpdateFromZip(String strZipPath, HashSet`1 lstFilesToDelete) in M:\Coding\chummer5a\Chummer\Utilities\frmUpdate.cs:line 611
   at Chummer.frmUpdate.cmdRestart_Click(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\Utilities\frmUpdate.cs:line 464
   at Chummer.frmUpdate.wc_DownloadCompleted(Object sender, AsyncCompletedEventArgs e) in M:\Coding\chummer5a\Chummer\Utilities\frmUpdate.cs:line 720
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.DownloadFileOperationCompleted(Object arg)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in M:\Coding\chummer5a\Chummer\Program.cs:line 113

**Comment by SeanPGorman** [comment]
Manually restarting shows version is now Version: 5.204

**Comment by chummer5a** [comment]
Should be fixed in the latest commits.
