### ISSUE TITLE
Chummer throws an error on character load if your Essense is over 6.

### ISSUE THREAD

**Issue by SydneySedai** [chummer5a/chummer5a#359]
Added a rating 200 Essense Antihole to simulate a Banshee using Essense Drain to go over the usual maximum of 6, ran into this error when I tried to reload that save data:

>************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '6' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected() in M:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 15085
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 564
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by joha4270** [comment]
I think i have a decent idea of what i happening, but could you please upload your .chum5 file too?

**Comment by SydneySedai** [comment]
http://pastebin.com/raw.php?i=XRRXg1Qa

**Comment by joha4270** [comment]
Thanks for the quick reply, i will look at it tomorrow (late here)
