### ISSUE TITLE
Cannot Select Magical Education Life Module

### ISSUE THREAD

**Issue by Arilus** [chummer5a/chummer5a#361]
I cannot successfully select the Magical Education Life Module. The corresponding Quality is applied to the character and then an error message pops up saying: "Object reference not set to an instance of an object." This persists whether the step is skipped until a Corporate Life Module is chosen or not.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Quality.Create(XmlNode objXmlQuality, Character objCharacter, QualitySource objQualitySource, TreeNode objNode, List`1 objWeapons, List`1 objWeaponNodes, String strForceValue) in M:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:line 1068
   at Chummer.frmCreate.cmdLifeModule_Click(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 7782
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by joha4270** [comment]
Found it, just a matter of a data file missing a field
