### ISSUE TITLE
NullReferenceException on opening Chummer5 file (5.131)

### ISSUE THREAD

**Issue by jflo** [chummer5a/chummer5a#381]
Not that i'm asserting this is supported usage ;) I'm trying to get some old characters 
`<createdversion>5.139</createdversion>`
`<appversion>5.139</appversion>`

working with the latest version. I suspect there is just some expected element missing. When I get home I'm going to try to diff older + newer versions of the xml to see if there is an obvious difference.

Assuming its not that simple, could someone guide me toward hacking these files so they can be opened by the newest version?

Thanks!

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Quality.Load(XmlNode objNode) in M:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:line 1241
   at Chummer.Character.Load() in M:\Coding\chummer5a\Chummer\Classes\clsCharacter.cs:line 1641
   at Chummer.frmMain.LoadCharacter(String strFileName, Boolean blnIncludeInMRU, String strNewName, Boolean blnClearFileName) in M:\Coding\chummer5a\Chummer\frmMain.cs:line 599
   at Chummer.frmMain.OpenFile(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\frmMain.cs:line 580
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18063 built by: FX45RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 0.5.173.0
    Win32 Version: 0.5.173.0
    CodeBase: file://fshbrs1/FlorentJ$/Desktop/Chummer5.173/Chummer5/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18036 built by: FX45RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18021 built by: FX45RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by joha4270** [comment]
Qualities are missing a <metagenetic> tag

From looking at source code in 30 seconds i'm not sure what the default
value should be, but next version will have it use a default if missing

**Comment by jflo** [comment]
oh thats huge. looks like it is empty but present by default.  

I added it to a problem file and now it opens.

+1 karma and ¥2K for you sir!

**Comment by joha4270** [comment]
You're Welcome

2015-09-14 22:31 GMT+02:00 Justin Florentine <notifications@github.com>:

**Comment by chummer5a** [comment]
ALready patched in the new version, for what it's worth. Try-catch saves
the day again

**Comment by chummer5a** [comment]
Fixed in 5.174.
