### ISSUE TITLE
(error) in 5.212.8 with chum5 files

### ISSUE THREAD

**Issue by Gitchum14** [chummer5a/chummer5a#4122]
**Describe the bug**
Start newest version to load character.
In latest version Character name is red with (error) behind it.
This happend across multiple character files not related to each other. 

**To Reproduce**
1. See Characters in list
2. Click on name
3. See description field

**Expected behavior**
Open Character

**Screenshots**

![grafik](https://user-images.githubusercontent.com/65242430/82947111-cd3a7c00-9f9f-11ea-9a5e-3fc6f021d7b6.png)

**Character File**
[Straßensamurai.txt](https://github.com/chummer5a/chummer5a/files/4684876/Strassensamurai.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.212.8 nightly

**Additional context**
Error text:

System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1721, position 73.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Chummer.CharacterCache..ctor(String strFile) in C:\projects\chummer\Chummer\Classes\clsCharacter.cs:line 17977

**Comment by Gitchum14** [comment]
Smartlink-Modi&#x1E or smiliar in the chum5 file is the error?

**Comment by Gitchum14** [comment]
Seems to be fixed, but files that are detected as corrupted are still not loading, work around is to remove them from chummer and reload them, this does not work for SINer saved files. 

Fixed.
