### ISSUE TITLE
Adding Weapon Mounts on Vehicles Causes Crash

### ISSUE THREAD

**Issue by martinezb3369** [chummer5a/chummer5a#4685]
### Environment
Crash ID: 77dda015-b8fa-4f1a-9029-ec206fbc86e9
Chummer Version: 5.220.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: ee682975-c621-451f-b6dd-aa201785ca20

### Expected behaviour
The pop up menu for weapon mounts to appear when selected.

### Actual behaviour
The program loads and then crashes.

### Steps to reproduce the behaviour
Have vehicle, attempt to add weapon mount. 

### Crash Description
Object reference not set to an instance of an object.
   at Chummer.CreateWeaponMount.RefreshComboBoxes() in C:\projects\chummer\Chummer\Forms\Creation Forms\CreateWeaponMount.cs:line 938
   at Chummer.CreateWeaponMount.frmCreateWeaponMount_Load(Object sender, EventArgs e) in C:\projects\chummer\Chummer\Forms\Creation Forms\CreateWeaponMount.cs:line 136
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message

**Comment by DelnarErsike** [comment]
Fixed in 2cddb7b07e4e0004933b422a7aa7dcaaf429751b.
