### ISSUE TITLE
Add Knowledge Skill Specialization Auto-Generated Issue from Crash: ID dd8c66e6-eb56-48a7-8d14-670650e4ad19

### ISSUE THREAD

**Issue by PirateSwayze** [chummer5a/chummer5a#4687]
### Environment
Crash ID: dd8c66e6-eb56-48a7-8d14-670650e4ad19
Chummer Version: 5.220.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: 272c85bc-d8be-409d-b7cc-8e3957036443

### Expected behaviour
Add Knowledge Skill with Specialization
### Actual behaviour
Application Crashes

### Steps to reproduce the behaviour
Add Knowledge Skill
Add Specialization
Change from Academic to Professional

### Crash Description
Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.Control.CreateGraphics()
   at Chummer.NumericUpDownEx.OnMarginChanged(Object sender, EventArgs e) in C:\projects\chummer\Chummer\Controls\Shared\Components\NumericUpDownEx.cs:line 95
   at System.Windows.Forms.Control.OnMarginChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Margin(Padding value)
   at Chummer.UI.Skills.KnowledgeSkillControl..ctor(KnowledgeSkill objSkill) in C:\projects\chummer\Chummer\Controls\Skills\KnowledgeSkillControl.cs:line 155
   at Chummer.UI.Skills.SkillsTabUserControl.

**Comment by DelnarErsike** [comment]
Cannot reproduce, it is likely that this was a one-off, especially if you had enough other characters open where Chummer ran out of the number of window handles it can create.
