### ISSUE TITLE
Auto-Generated Issue from Crash: ID bff2ac2c-0a30-4a93-bb04-3a908dd922d5

### ISSUE THREAD

**Issue by KitKat31337** [chummer5a/chummer5a#4701]
### Environment
Crash ID: bff2ac2c-0a30-4a93-bb04-3a908dd922d5
Chummer Version: 5.221.0
Environment: Windows 10 Enterprise
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: 26c03117-f599-4eb9-9d6d-292df31ecc7d

### Expected behaviour
Import Hero Lab

### Actual behaviour
Crashes to Desktop

### Steps to reproduce the behaviour
Try to import a hero lab file

### Crash Description
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Chummer.HeroLabImporter.CacheCharacters(String strFile) in C:\projects\chummer\Chummer\Forms\Utility Forms\HeroLabImporter.cs:line 92
   at Chummer.HeroLabImporter.cmdSelectFile_Click(Object sender, EventArgs e) in C:\projects\chummer\Chummer\Forms\Utility Forms\HeroLabImporter.cs:line 59
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message

**Comment by ArchonMegalon** [comment]
Hi @KitKat31337 !

Can you please supply the HeroLabFile?
