### ISSUE TITLE
Chummer crashed, cant be opened or downloaded

### ISSUE THREAD

**Issue by crimsonrebel** [chummer5a/chummer5a#4703]
Ever since this crash Chummer has failed to open.  I've deleted all files, restarted the PC and downloaded again 3 times with the same results.  2 others on reddit said the same has happened to them.

**Describe the bug**

This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.ArgumentOutOfRangeException: Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.CharacterCreate.UpdateQualityLevelValue(Quality objSelectedQuality) in C:\projects\chummer\Chummer\Forms\Character Forms\CharacterCreate.cs:line 6848
   at Chummer.CharacterCreate.UpdateCharacterInfo(Object sender, EventArgs e) in C:\projects\chummer\Chummer\Forms\Character Forms\CharacterCreate.cs:line 9960
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:line 498
Crash id is 9bbcfa75-77bb-4492-a60e-82ec35cc87c4
Crash working directory is C:\Users\Rodney\AppData\Local\Temp\chummer_crash_132896225230086291

**Comment by DelnarErsike** [comment]
The actual crash itself has been fixed in the Nightly already. As for being unable to be opened or downloaded, that sounds like an issue with your anti-virus software.
