### ISSUE TITLE
Auto-Generated Issue from Crash: ID 678fe6f4-ab8b-4f09-bbe5-afa63829b8ba

### ISSUE THREAD

**Issue by busbyra** [chummer5a/chummer5a#4759]
### Environment
Crash ID: 678fe6f4-ab8b-4f09-bbe5-afa63829b8ba
Chummer Version: 5.222.52
Environment: Windows 10 Education
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 6118a8b2-2e62-46e2-b90e-5c10873cdaaa

### Expected behaviour
Expected to have Improved Reflexes added to the sheet
### Actual behaviour
Chummer and Chummer Nightly both crash.
.
### Steps to reproduce the behaviour
Create a character, select Adept Powers, Select Improved Reflexes.  Select Add

### Crash Description
Controls created on one thread cannot be parented to a control on a different thread.
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at Chummer.UI.Table.TableView`1.ItemsChanged(Object sender, ListChangedEventArgs e) in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:line 559
   at System.ComponentModel.ListChangedEventHandler.Invoke(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.BindingList`1.OnListChanged(ListChangedEventArgs e)
   at Chummer.ThreadSafeBindingList`1.OnListChanged(ListChangedEventArgs e) in C:\projects\chummer\Chummer\Backend\Datastructures\ThreadSafeBindingList.cs:line 89
   at System.ComponentModel.BindingList`1.FireListChanged(ListChangedType type, Int32 index)
   at System.ComponentModel.BindingList`1.InsertItem(Int32 index, T item)
   at Chummer.ThreadSafeBindingList`1.InsertItem(Int32 index, T item) in C:\projects\chummer\Chummer\Backend\Datastructures\ThreadSafeBindingList.cs:line 235
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Chummer.UI.Powers.PowersTabUserControl.

**Comment by DelnarErsike** [comment]
Should be fixed as of in 5.222.61.
