### ISSUE TITLE
Auto-Generated Issue from Crash: ID aefddfb3-6b0b-411d-aee4-88614f0190a6

### ISSUE THREAD

**Issue by DrakTheDragon** [chummer5a/chummer5a#4768]
### Environment
Crash ID: aefddfb3-6b0b-411d-aee4-88614f0190a6
Chummer Version: 5.222.61
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 8371790b-e9d8-4800-a537-74c88a095f3b

### Expected behaviour
Adding Powers to Adept in Character Creation

### Actual behaviour
Create new Character as Adept, select Add Power, Select Power, click OK - Chummer crashes.  Multiple Powers tried - all same result.

### Steps to reproduce the behaviour

Crash followup Id = cb42d74b-c3c7-4499-84e3-b9237acc1d80

Installation Id = 8371790b-e9d8-4800-a537-74c88a095f3b

Controls created on one thread cannot be parented to a control on a different thread

### Crash Description
Controls created on one thread cannot be parented to a control on a different thread.
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at Chummer.UI.Table.TableView`1.ItemsChanged(Object sender, ListChangedEventArgs e) in C:\projects\chummer\Chummer\Controls\Table\TableView.cs:line 559
   at System.ComponentModel.ListChangedEventHandler.Invoke(Object sender, ListChangedEventArgs e)
   at System.ComponentModel.BindingList`1.OnListChanged(ListChangedEventArgs e)
   at Chummer.ThreadSafeBindingList`1.OnListChanged(ListChangedEventArgs e) in C:\projects\chummer\Chummer\Backend\Datastructures\ThreadSafeBindingList.cs:line 90
   at System.ComponentModel.BindingList`1.FireListChanged(ListChangedType type, Int32 index)
   at System.ComponentModel.BindingList`1.InsertItem(Int32 index, T item)
   at Chummer.ThreadSafeBindingList`1.InsertItem(Int32 index, T item) in C:\projects\chummer\Chummer\Backend\Datastructures\ThreadSafeBindingList.cs:line 236
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Chummer.UI.Powers.PowersTabUserControl.

**Comment by DrakTheDragon** [comment]
Have repeated attempts for over a week.  Have tried Clean Reinstall tool within Chummer.  No effect - same crash each time.  Issue affects brand new Characters, started as a Test just today, and Characters left in library in the process of creation since several months ago.

**Comment by DelnarErsike** [comment]
Should be fixed in 5.222.66.
