### ISSUE TITLE
Character saving fails due to XML Parser errors with natural weapons (trolls/drake)

### ISSUE THREAD

**Issue by Knick72** [chummer5a/chummer5a#4769]
Here is the warning that is logged:
2022-04-13 04:44:51.1272 WARN System.Xml.XmlException: The 'naturalweapons' start tag on line 3679 position 732 does not match the end tag of 'firstlevelbonus'. Line 3679, position 961.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Chummer.Character.Save(String strFileName, Boolean addToMRU, Boolean callOnSaveCallBack) in C:\projects\chummer\Chummer\Backend\Characters\Character.cs:line 3066

At first i got that error with activated Custom Data "Trolls have natural weapon Horns". By deactivating that custom data, i could work around that error when saving trolls. The same warning still occurs with my troll drake - probably due to drake natural weapons - and saving is aborted with an error warning.

**Comment by DelnarErsike** [comment]
Known issue, already fixed in the Nightly.
