### ISSUE TITLE
Purchasing a vehicle with a built-in weapon causes a crash

### ISSUE THREAD

**Issue by chummer5a** [chummer5a/chummer5a#4775]
**Describe the bug**
When attempting to add the F-B Bumblebee drone, or any other vehicle that comes with a weapon pre-installed (Ares Duelist, etc.), a duplicate semaphore error occurs.

**Version**
Current as of https://github.com/chummer5a/chummer5a/commit/577187b8b9b885bbf4324705a36d00fd8b6694a7

**Reproduction**
Create a new character, switch to vehicles tab, purchase a drone with a pre-installed weapon. 

Fault does not exist when purchasing a vehicle that only has weapon mounts, so is presumably a thread-issue in how it checks for the total nuyen cost of the weapons attached to the mount. 

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Current and next semaphores are identical, this should not happen.
  Source=Chummer5
  StackTrace:
   at Chummer.AsyncFriendlyReaderWriterLock.SafeWriterSemaphoreRelease..ctor(DebuggableSemaphoreSlim objLastSemaphore, DebuggableSemaphoreSlim objCurrentSemaphore, DebuggableSemaphoreSlim objNextSemaphore, AsyncFriendlyReaderWriterLock objReaderWriterLock) in c:\source\repos\chummer5a\chummer5a\Chummer\Backend\Helpers\AsyncFriendlyReaderWriterLock.cs:line 385
   at Chummer.AsyncFriendlyReaderWriterLock.EnterWriteLock(CancellationToken token) in c:\source\repos\chummer5a\chummer5a\Chummer\Backend\Helpers\AsyncFriendlyReaderWriterLock.cs:line 63
   at Chummer.Character.set_Nuyen(Decimal value) in c:\source\repos\chummer5a\chummer5a\Chummer\Backend\Characters\Character.cs:line 20315
   at Chummer.CharacterCreate.<CalculateNuyen>d__261.MoveNext() in c:\source\repos\chummer5a\chummer5a\Chummer\Forms\Character Forms\CharacterCreate.cs:line 10892
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Chummer.CharacterCreate.<DoUpdateCharacterInfo>d__260.MoveNext() in c:\source\repos\chummer5a\chummer5a\Chummer\Forms\Character Forms\CharacterCreate.cs:line 10801
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chummer.CharacterShared.<RequestCharacterUpdate>d__114.MoveNext() in c:\source\repos\chummer5a\chummer5a\Chummer\Forms\Character Forms\CharacterShared.cs:line 8095
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Chummer.CharacterShared.<MakeDirtyWithCharacterUpdate>d__109.MoveNext() in c:\source\repos\chummer5a\chummer5a\Chummer\Forms\Character Forms\CharacterShared.cs:line 8010

  This exception was originally thrown at this call stack:
    Chummer.AsyncFriendlyReaderWriterLock.SafeWriterSemaphoreRelease.SafeWriterSemaphoreRelease(Chummer.DebuggableSemaphoreSlim, Chummer.DebuggableSemaphoreSlim, Chummer.DebuggableSemaphoreSlim, Chummer.AsyncFriendlyReaderWriterLock) in AsyncFriendlyReaderWriterLock.cs
    Chummer.AsyncFriendlyReaderWriterLock.EnterWriteLock(System.Threading.CancellationToken) in AsyncFriendlyReaderWriterLock.cs
    Chummer.Character.Nuyen.set(decimal) in Character.cs
    Chummer.CharacterCreate.CalculateNuyen(System.Threading.CancellationToken) in CharacterCreate.cs
    [External Code]
    Chummer.CharacterCreate.DoUpdateCharacterInfo(System.Threading.CancellationToken) in CharacterCreate.cs
    [External Code]
    Chummer.CharacterShared.RequestCharacterUpdate() in CharacterShared.cs
    [External Code]
    Chummer.CharacterShared.MakeDirtyWithCharacterUpdate(object, System.Collections.Specialized.NotifyCollectionChangedEventArgs) in CharacterShared.cs
```

**Comment by DelnarErsike** [comment]
Yup, this is the thing I've been struggling with for about a month now, I just made it more overt (i.e. cause an exception) when the bug triggers instead of allowing it to deadlock a background task. It's fixed in a super-hacky way in cabd8d4baf48e92cc11402cb480f469b60fca534.
