### ISSUE TITLE
Auto-Generated Issue from Crash: ID ff4efa44-1091-4abc-a26a-37a61fa5d034

### ISSUE THREAD

**Issue by MangoCobra** [chummer5a/chummer5a#4785]
### Environment
Crash ID: ff4efa44-1091-4abc-a26a-37a61fa5d034
Chummer Version: 5.222.80
Environment: Windows 10 Home
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: be72120e-bfec-4017-8388-7658569cb143

### Expected behaviour
I wanted to be able to add Shock Frills to my armor
I also wanted to remove grenades from my character sheet
### Actual behaviour
Chummer Crashed for the shock frills
Chummer removed the grenades from the gear section but not the weapons section
### Steps to reproduce the behaviour
Add shock frills to armor causes a crash
Add grenades to gear and then delete.
### Crash Description
Object reference not set to an instance of an object.
   at Chummer.Backend.Equipment.Weapon.Create(XmlNode objXmlWeapon, ICollection`1 lstWeapons, Boolean blnCreateChildren, Boolean blnCreateImprovements, Boolean blnSkipCost, Int32 intRating) in C:\projects\chummer\Chummer\Backend\Equipment\Weapon.cs:line 328
   at Chummer.Backend.Equipment.ArmorMod.Create(XmlNode objXmlArmorNode, Int32 intRating, IList`1 lstWeapons, Boolean blnSkipCost, Boolean blnSkipSelectForms) in C:\projects\chummer\Chummer\Backend\Equipment\ArmorMod.cs:line 296
   at Chummer.CharacterCreate.

**Comment by DelnarErsike** [comment]
It seems like most of this is due to a badly created custom dataset (Chummer is trying to add a weapon that doesn't exist, but it's doing so because something that is not the vanilla data files is telling it to), but the crash can be fixed.
