### ISSUE TITLE
0.5.176 Machine Pistols

### ISSUE THREAD

**Issue by SB-FM** [chummer5a/chummer5a#482]
All entries in the Machine Pistols Category are listed as "Chummer.List Item"
Selecting them leads to 

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, ContextMenuStrip cmsWeaponMod, Boolean blnCreateChildren) in C:\Users\joha4\Desktop\chummer5a-master\Chummer\Classes\clsEquipment.cs:line 4434
   at Chummer.frmSelectWeapon.lstWeapon_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\joha4\Desktop\chummer5a-master\Chummer\frmSelectWeapon.cs:line 130
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Known issue; it received a stealth patch via the auto-updater, but it will be included in 5.177.
