### ISSUE TITLE
random crash post-update to 5.222.0.0

### ISSUE THREAD

**Issue by AdonaiShadowblade** [chummer5a/chummer5a#4826]
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.UnauthorizedAccessException: Access to the path 'E:\$RECYCLE.BIN\S-1-5-21-467915138-2798718690-1339000802-500' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Chummer.frmUpdate.cmdRestart_Click(Object sender, EventArgs e) in M:\Coding\chummer5a\Chummer\Utilities\frmUpdate.cs:line 431
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Chummer.Program.Main() in M:\Coding\chummer5a\Chummer\Program.cs:line 396
Crash id is 215b181b-b40a-4a6b-9fef-f043c2ad1406
Crash working directory is C:\Users\link1\AppData\Local\Temp\chummer_crash_132995833726835040
this is the crash report it generated upon attempting to launch, i've tried re-installing multiple times, fully deleting the files each time, the report is identical each time,

**Comment by JoschiGrey** [comment]
Chummer tries to access a file in your recycling bin, which is denied by windows.
Did you by any chance try to open a character right before this crash occured?

**Comment by AdonaiShadowblade** [comment]
> 

no actually, i had everything exited out, even fully deleted the files and emptied my bin, and it's still doing it,

**Comment by chummer5a** [comment]
I think this may have been resolved post-5.222.134, Does it still occur for you in a recent nightly build?
