### ISSUE TITLE
Opening clicking on weapons on old characters produce a argument out of range exception

### ISSUE THREAD

**Issue by JoschiGrey** [chummer5a/chummer5a#4844]
Example Characters
[Kemist After BReak Alt.txt](https://github.com/chummer5a/chummer5a/files/9030290/Kemist.After.BReak.Alt.txt)
[heX.txt](https://github.com/chummer5a/chummer5a/files/9030309/heX.txt)

```c#
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Chummer.Backend.Equipment.Weapon.GetClip(Int32 clip) in F:\Programming\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 7131
   at Chummer.Backend.Equipment.Weapon.get_AmmoLoaded() in F:\Programming\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 2010
   at Chummer.Backend.Equipment.Weapon.<CalculatedDamageCoreAsync>d__302.MoveNext() in F:\Programming\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 2712
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Chummer.Backend.Equipment.Weapon.CalculatedDamage(CultureInfo objCulture, String strLanguage) in F:\Programming\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 2508
   at Chummer.Backend.Equipment.Weapon.get_DisplayDamage() in F:\Programming\chummer5a\Chummer\Backend\Equipment\Weapon.cs:line 2501
   at Chummer.CharacterCareer.<>c__DisplayClass372_2.<RefreshSelectedWeapon>b__45(Label x) in F:\Programming\chummer5a\Chummer\Forms\Character Forms\CharacterCareer.cs:line 15097
   at Chummer.WinFormsExtensions.<>c__DisplayClass15_0`1.<DoThreadSafeAsync>b__1() in F:\Programming\chummer5a\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:line 705
   at Chummer.Utils.RunOnMainThreadAsync(Action func, CancellationToken token) in F:\Programming\chummer5a\Chummer\Backend\Static\Utils.cs:line 1278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chummer.WinFormsExtensions.<DoThreadSafeAsync>d__15`1.MoveNext() in F:\Programming\chummer5a\Chummer\Backend\Static\Extensions\WinFormsExtensions.cs:line 732
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chummer.CharacterCareer.<RefreshSelectedWeapon>d__372.MoveNext() in F:\Programming\chummer5a\Chummer\Forms\Character Forms\CharacterCareer.cs:line 15097
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Chummer.CharacterCareer.<RefreshSelectedWeapon>d__372.MoveNext() in F:\Programming\chummer5a\Chummer\Forms\Character Forms\CharacterCareer.cs:line 15746
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Chummer.CharacterCareer.<treWeapons_AfterSelect>d__234.MoveNext() in F:\Programming\chummer5a\Chummer\Forms\Character Forms\CharacterCareer.cs:line 11233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by chummer5a** [comment]
Resolved in nightlies, I think? Pretty sure this was the clip big where it wasn't properly generating the new clip.
