### ISSUE TITLE
Weapon Accessory Problem Since Nightly-v1.0.537

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#494]
Problem seems to have gotten worse in build Nightly-v1.0.542. Replicated these steps and got an error for any accessory. Logged that as #521.

Hi, I'm getting an error when I try to add a spare clip to a Predator V. This has been happening since Nightly-v1.0.537.:

Test Case:
1 - Download Nightly-v1.0.537 zip file. 
2 - Extract
3 - Double Click Chummer5.exe
4 - Go into options menu because it's first time opening this version, click ok with only sr5 book chosen
5 - Click create new runner icon 
6 - Priority Build with Default entries. Adept 6. Aeronautical mechanic.
7 - Go to street gear. Add Predator V Heavy Pistol
8 - Right click on Predator v Heavy pistol and choose 'Add Accessory'
9 - Choose 'Spare Clip'.
10 - Error. Error text below:
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectWeaponAccessory.get_SelectedMount() in C:\projects\chummer5a\Chummer\frmSelectWeaponAccessory.cs:line 260
   at Chummer.frmCreate.tsWeaponAddAccessory_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 8897
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by whatevs5** [comment]
Tried to replicate steps. Got an error trying to add any accessory to a weapon.

**Comment by whatevs5** [comment]
Tried to replicate steps for build Nightly-v1.0.545. Issue seems to be fixed. Thanks! Closing ticket.
