### ISSUE TITLE
Character sheet crash

### ISSUE THREAD

**Issue by samitefan1** [chummer5a/chummer5a#5108]
**Describe the bug**
On exiting character, chummer fails to create crash report due to error in crash handler

**To Reproduce**
1. Close character
2. See error message (Contents dumped in additional info section

**Expected behavior**
Chummer closing character sheet without crashing

**Screenshots**
![1](https://github.com/chummer5a/chummer5a/assets/20809343/1cd63b21-48a3-41d2-aecc-bdee9e6602d4)
![2](https://github.com/chummer5a/chummer5a/assets/20809343/3d2f7437-cc0a-4a9c-ab23-fe677126f627)

**Character File**
See below comment for character file

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 5.225.307

**Additional context**
Failed to create crash report because of an issue with the crash handler.
Chummer crashed with version: 5.225.307.0
Crash Handler crashed with exit code: -532462766
Crash information:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AsyncFriendlyReaderWriterLock'.
   at Chummer.AsyncFriendlyReaderWriterLock.EnterWriteLock(CancellationToken token) in C:\projects\chummer\Chummer\Backend\Helpers\AsyncFriendlyReaderWriterLock.cs:line 65
   at Chummer.SpiritControl.UnbindSpiritControl() in C:\projects\chummer\Chummer\Controls\Characters\SpiritControl.cs:line 120
   at Chummer.SpiritControl.<.ctor>b__8_0(Object sender, EventArgs args) in C:\projects\chummer\Chummer\Controls\Characters\SpiritControl.cs:line 51
   at System.ComponentModel.Component.Dispose(Boolean disposing)
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at Chummer.SpiritControl.Dispose(Boolean disposing) in C:\projects\chummer\Chummer\Controls\Characters\SpiritControl.Designer.cs:line 20
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.ContainerControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.TabControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.ContainerControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at Chummer.CharacterShared.Dispose(Boolean disposing) in C:\projects\chummer\Chummer\Forms\Character Forms\CharacterShared.cs:line 9368
   at Chummer.CharacterCareer.Dispose(Boolean disposing) in C:\projects\chummer\Chummer\Forms\Character Forms\CharacterCareer.Designer.cs:line 23
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by samitefan1** [comment]
[FunkSHCareertest.txt](https://github.com/chummer5a/chummer5a/files/14230815/FunkSHCareertest.txt)

**Comment by samitefan1** [comment]
Closing because issue does not occur in newest nightly.
