### ISSUE TITLE
Error - Adding an Accessory to a Weapon Nightly-v1.0.544

### ISSUE THREAD

**Issue by whatevs5** [chummer5a/chummer5a#521]
Update: 
v1.0.544  - Still get this error.
v1.0.542 - I get an error when trying to add any accessory to a weapon, not just speedloaders.

As per #501 I probably shouldn't be allowed to add speed loaders for any weapon that isn't a revolver, but when I try to replicate the issue from #501 I now get an error.

Step 1 - Add Predator V to weapons
Step 2 - Right click > Add Accessory > Speed Loader
Step 3 - Click Okau. Error. Error text and screenshot:
![image](https://cloud.githubusercontent.com/assets/15821037/11214864/7fa42e5a-8d11-11e5-9da2-b738050d603d.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmSelectWeaponAccessory.get_SelectedMount() in C:\projects\chummer5a\Chummer\frmSelectWeaponAccessory.cs:line 260
   at Chummer.frmCreate.tsWeaponAddAccessory_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 8897
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Kyoto-Kid** [comment]
..been experiencing the same issue. Addressed this on the Chummer Support thread over on teh Shadowrun Forums.

**Comment by chummer5a** [comment]
Similar but different. This comes from the accessories that don't have a slot; I didn't code in the Internal/External slots, so for things like Spare Clips it crashes out. Will be fixed in the next version.

**Comment by Kyoto-Kid** [comment]
..thank you.  Any idea on when that will be?

**Comment by whatevs5** [comment]
Just re-ran the test steps for v1.0.544. Still getting the same problem.

**Comment by whatevs5** [comment]
Just reran the test steps for  177 and v1.0.545. Looks like it's fixed. Thanks so much!

**Comment by Kyoto-Kid** [comment]
...so do I need to download ver. 177 again?

**Comment by whatevs5** [comment]
That's how I did it. I just downloaded v1.0.545 and  Build 177 from the 'Releases' tab. Then I ran those versions from their own folders.

**Comment by Kyoto-Kid** [comment]
...I downloaded ver. 177 two days ago is that the same one?

**Comment by Kyoto-Kid** [comment]
...installed ver. 177 and still getting the Unhandled Exception error when selecting a commlink along with no Commlink attributes being displayed in the description.

**Comment by chummer5a** [comment]
It's fixed in 5.178. As an interim workaround, make sure your commlink is
the first item in the gear window. You can use rightclick to drag it to the
top.

**Comment by Kyoto-Kid** [comment]
...thanks
