### ISSUE TITLE
Issues with Infected and Initiative

### ISSUE THREAD

**Issue by Gamingharry** [chummer5a/chummer5a#525]
Hello, Massive fan!

Currently facing this issue when adding the Vamp human quality. After selecting the attributes and optional powers I get an "Unhandled Exception has occurred" error with the exception text details below. 

Took a look at the Qualities.xml file and found that during the powers section Essence drain, Infection and Age imminuty where added but 
"<power>Essense Loss</power>
<power>Dual Natured</power>
<power>Infection</power>
<power select="Wood, Severe">Allergy</power>
<power select="Sunlight, Severe">Allergy</power>
<power select="Metahuman Blood">Dietary Requirement</power>
<power select="Lack of Air (Essence) Minutes">Induced Dormancy</power>"
Don't seem to run as I have none of these talents. 

Also it seems that I have not had the extra +1 Initiative dice added to the character. Is this my setup or an issue with the Program?

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Quality.Create(XmlNode objXmlQuality, Character objCharacter, QualitySource objQualitySource, TreeNode objNode, List`1 objWeapons, List`1 objWeaponNodes, String strForceValue) in D:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:line 1063
   at Chummer.frmCreate.AddQuality(XmlNode objXmlAddQuality, XmlNode objXmlSelectedQuality, List`1 objWeapons, List`1 objWeaponNodes) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 8072
   at Chummer.frmCreate.cmdAddQuality_Click(Object sender, EventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 7944
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
You're not getting the extra qualities because of the crash. The crash itself is because the weapon it's trying to add (The bite attack) doesn't exist. Will be fixed shortly.

**Comment by Gamingharry** [comment]
Hi, 
It was a fresh download that didn't work. Tried another clean download on a new PC same issue. That new .xml file hasnt helped either :(

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.CritterPower.Create(XmlNode objXmlPowerNode, Character objCharacter, TreeNode objNode, Int32 intRating, String strForcedValue) in D:\Coding\chummer5a\Chummer\Classes\clsUnique.cs:line 9226
   at Chummer.frmCreate.cmdAddQuality_Click(Object sender, EventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 7969
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chummer5a** [comment]
Nuts, typo in the qualities file. Sorry about that. It'll be fixed in the next version, but if you want to just open up qualities.xml and replace 'essense' with 'essence' it'll work.

**Comment by Gamingharry** [comment]
Tweaked it and worked! Fantastic! :) 

Have noticed though that I'm not getting the +1d6 on initiative nor are the metatype limits being edited.

Still thanks a bunch! :)

**Comment by chummer5a** [comment]
Fixed in 5.178.
