### ISSUE TITLE
Rigger Command Console Crash During Creation

### ISSUE THREAD

**Issue by xlorxpinnacle** [chummer5a/chummer5a#534]
I got a "Unhandled exception has occurred in your application. Unable to cast object of type 'Chummer.Gear' to type 'Chummer.Commlink' after clicking on my RCC in my gear section following the addition of fake licenses.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Chummer.Gear' to type 'Chummer.Commlink'.
   at Chummer.CommonFunctions.FindCommlink(String strGuid, List`1 lstCommlink) in D:\Coding\chummer5a\Chummer\Classes\clsCommon.cs:line 77
   at Chummer.frmCreate.cboGearSleaze_SelectedIndexChanged(Object sender, EventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 13478
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at Chummer.frmCreate.RefreshSelectedGear() in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 18377
   at Chummer.frmCreate.treGear_AfterSelect(Object sender, TreeViewEventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 12909
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18444 built by: FX451R

**Comment by chummer5a** [comment]
Fixed in 5.178.

**Comment by xlorxpinnacle** [comment]
Thank you! I noticed, and really appreciated it!
