### ISSUE TITLE
ArgumentOutOfRangeException when opening older character files

### ISSUE THREAD

**Issue by Fightbackman** [chummer5a/chummer5a#544]
When I try to open an older character files with the current chummer version the following exception occurs:

System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
  ParamName=Value
  Source=System.Windows.Forms
  StackTrace:
       at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
       at Chummer.ContactControl.set_ConnectionRating(Int32 value) in C:\Users\Lukas\Documents\GitHub\chummer5a\Chummer\Controls\ContactControl.cs:line 472
       at Chummer.frmCareer.frmCareer_Load(Object sender, EventArgs e) in C:\Users\Lukas\Documents\GitHub\chummer5a\Chummer\frmCareer.cs:line 711
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException: 

I add the character i file i used.
https://www.firepulse.de/owncloud/index.php/s/p3XPGZGfY5Puz5R
pw: chumer

**Comment by chummer5a** [comment]
You have a contact (John Spazz Silver) that has a Connection Rating of 0, which is what causes the error. The RAW restriction is that contacts have a minimum loyalty and connection of 1. Easiest way to fix it is to change the connection rating to 1.

**Comment by Fightbackman** [comment]
Oh yeah you'r right. But i think an exception handling would be nice.
