### ISSUE TITLE
Unhandled NullReferenceException on adding lifestyle

### ISSUE THREAD

**Issue by Fightbackman** [chummer5a/chummer5a#545]
When adding a lifestyle for a completly new char lifestyle chummer throws an NullReference Exception:

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Chummer5
  StackTrace:
       at Chummer.frmSelectLifestyle.CalculateValues(Boolean blnIncludePercentage) in C:\Users\Lukas\Documents\GitHub\chummer5a\Chummer\frmSelectLifestyle.cs:line 309
       at Chummer.frmSelectLifestyle.frmSelectAdvancedLifestyle_Load(Object sender, EventArgs e) in C:\Users\Lukas\Documents\GitHub\chummer5a\Chummer\frmSelectLifestyle.cs:line 141
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException: 

I'll reproduced that exception on three different systems.

**Comment by chummer5a** [comment]
Missing required values for the hospitalized lifestyles. Fixed in 5.179.
