### ISSUE TITLE
Tactical Grapple Gun not working

### ISSUE THREAD

**Issue by davidtrest** [chummer5a/chummer5a#565]
Looks like the Tactical Grapple Gun may not be configured correctly. Attempting to add it results in a runtime error:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, ContextMenuStrip cmsWeaponMod, Boolean blnCreateChildren) in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 4423
   at Chummer.Gear.Create(XmlNode objXmlGear, Character objCharacter, TreeNode objNode, Int32 intRating, List`1 objWeapons, List`1 objWeaponNodes, String strForceValue, Boolean blnHacked, Boolean blnInherent, Boolean blnAddImprovements, Boolean blnCreateChildren, Boolean blnAerodynamic) in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 10349
   at Chummer.frmCreate.PickGear() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 19112
   at Chummer.frmCreate.cmdAddGear_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 6414
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at SplitButton.OnMouseUp(MouseEventArgs mevent) in C:\projects\chummer5a\Chummer\SplitButton.cs:line 298
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at SplitButton.WndProc(Message& m) in C:\projects\chummer5a\Chummer\SplitButton.cs:line 805
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I think the Exotic Ranged Weapon may not be written, since I see one for similar gear (Grapple Gun, Micro Flare Launcher, etc.).

**Comment by chummer5a** [comment]
Yeah, the actual weapon doesn't exist. Will be fixed in 5.179.
