### ISSUE TITLE
Certain Gear and Weapon Menus Not Working

### ISSUE THREAD

**Issue by ryan5w4** [chummer5a/chummer5a#569]
When I try to open the Assault Rifle list, for most of the weapons, when you click on them, it gives this error message: "Object reference not set to an instance of an object." The exception text is:
_________________________________________________________________________________

 System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Weapon.Create(XmlNode objXmlWeapon, Character objCharacter, TreeNode objNode, ContextMenuStrip cmsWeapon, ContextMenuStrip cmsWeaponAccessory, ContextMenuStrip cmsWeaponMod, Boolean blnCreateChildren)
   at Chummer.frmSelectWeapon.lstWeapon_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

_________________________________________________________________________________

(Sorry for the bad formatting, it wouldn't allow me to make it look better.)

After seeing this, I tried to use other weapon menus. Most of them do not work, except for certain guns in each menu. The sniper rifle menu has no weapon names, only "Chummer.ListItem," as well as the Submachine Gun list, the Sporting Rifle list, the Light Machine Gun list, and everything below that besides Missile Launchers. Thanks for helping!

**Comment by chummer5a** [comment]
You're using 5.177. Please update via the
gihub.com/chummer5a/chummer5a/releases/latest link.

**Comment by ryan5w4** [comment]
Ah, thank you!
