### ISSUE TITLE
Special > Change Priority Selection does not work for Sum to Ten

### ISSUE THREAD

**Issue by Tathas** [chummer5a/chummer5a#572]
It presents an error dialog.  If you continue, the priority selection dialog is non-functional.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at Chummer.frmSumtoTenMetatype.LoadMetatypes()
   at Chummer.frmSumtoTenMetatype.frmSumtoTenMetatype_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by E-Strange** [comment]
When I try sum-to-10, it starts with all the skill and attribute points spent, and charges karma for any points spent.

**Comment by chummer5a** [comment]
Yup. I'm an idiot and only coded Sum to Ten using different variables to
Priority mode originally, so it doesn't work. I'll have it fixed up
sometime this week.

**Comment by chummer5a** [comment]
Fixed in 5.179.
