### ISSUE TITLE
When taking unable to take the chaos mentor in latest nightly  Error report inside

### ISSUE THREAD

**Issue by cormanater** [chummer5a/chummer5a#661]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.ImprovementManager.ProcessBonus(ImprovementSource objImprovementSource, String& strSourceName, Boolean blnConcatSelectedValue, Int32 intRating, String strFriendlyName, XmlNode bonusNode, String strUnique) in C:\projects\chummer5a\Chummer\Classes\clsImprovement.cs:line 3439
   at Chummer.ImprovementManager.CreateImprovements(ImprovementSource objImprovementSource, String strSourceName, XmlNode nodBonus, Boolean blnConcatSelectedValue, Int32 intRating, String strFriendlyName, Object fCreate) in C:\projects\chummer5a\Chummer\Classes\clsImprovement.cs:line 962
   at Chummer.ImprovementManager.ProcessBonus(ImprovementSource objImprovementSource, String& strSourceName, Boolean blnConcatSelectedValue, Int32 intRating, String strFriendlyName, XmlNode bonusNode, String strUnique) in C:\projects\chummer5a\Chummer\Classes\clsImprovement.cs:line 2878
   at Chummer.ImprovementManager.CreateImprovements(ImprovementSource objImprovementSource, String strSourceName, XmlNode nodBonus, Boolean blnConcatSelectedValue, Int32 intRating, String strFriendlyName, Object fCreate) in C:\projects\chummer5a\Chummer\Classes\clsImprovement.cs:line 962
   at Chummer.Quality.Create(XmlNode objXmlQuality, Character objCharacter, QualitySource objQualitySource, TreeNode objNode, List`1 objWeapons, List`1 objWeaponNodes, String strForceValue) in C:\projects\chummer5a\Chummer\Classes\clsUnique.cs:line 1211
   at Chummer.frmCreate.cmdAddQuality_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 7819
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.679.0
    Win32 Version: 5.179.679
    CodeBase: file:///E:/RPG/Shadowrun%205E/Character%20gen/Chummer%20Nightly/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by chummer5a** [comment]
Oops. I thought I removed all those qualities. Should be fixed in the next update.

**Comment by cormanater** [comment]
Just for clarification is was the increase of the physical limit by 2 as an adept that looked like it screwed it

**Comment by chummer5a** [comment]
Fixed in the latest commit.
