### ISSUE TITLE
Adding Adept Powers throws unhandled exception

### ISSUE THREAD

**Issue by tradloff** [chummer5a/chummer5a#690]
Preface: This may be a Linux-related problem. But still.

Steps to recreate the problem:

1. create new adept or mystic adept character
1a. if mystic adept: buy one or more power points
2. open "Add Power" dialog
3. choose any power, press "OK"

Result: Unhandled FormatException (output below). It occurs while converting the power's point cost value from string to integer.

System: I'm running Chummer 5.178 on GNU/Linux (Debian Jessie), using the latest official wine version (1.9.3) and .NET 4.5.2 installed via winetricks.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDecimal(String value, IFormatProvider provider)
   at Chummer.frmSelectPower.AcceptForm() in C:\projects\chummer5a\Chummer\frmSelectPower.cs:line 355
   at Chummer.frmSelectPower.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\frmSelectPower.cs:line 85
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 0.5.178.0
    Win32 Version: 0.5.178.0
    CodeBase: file:///Z:/home/username/RPG/Shadowrun/Chummer5/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by chummer5a** [comment]
Can you try one of the nightly builds? I think I know what was wrong here, can't remember if I fixed it or not.

**Comment by tradloff** [comment]
I tried the latest nightly and got the exact same error (output below).

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDecimal(String value, IFormatProvider provider)
   at Chummer.frmSelectPower.AcceptForm() in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectPower.cs:line 355
   at Chummer.frmSelectPower.cmdOK_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Selection Forms\frmSelectPower.cs:line 85
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.715.0
    Win32 Version: 5.179.715
    CodeBase: file:///Z:/home/username/RPG/Shadowrun/Chummer.Nightly.v5.179.715/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by joha4270** [comment]
Just to be sure, does this happen to every adept power or only some few?

**Comment by tradloff** [comment]
All of them.

**Comment by tradloff** [comment]
I found the source of the problem with string-to-number conversion: It's the decimal point.

In the "powers.xml" file, fractions in the `<points>` and `<adeptway>` fields are written with a decimal point and without a leading zero (e.g.`.5`  and `.25` for Killing hands). If you change the points into commas, you can add the power without error. Right now every power in the file throw the error because all of them have a fraction in either <points> or <adeptway>.

There is a problem with leading zeroes, too. If I change the Killing Hands cost to `0.5`, the conversion doesn't throw an error anymore but returns the wrong value (five instead of one half). It's the same with cyberware that costs fractions of essence points: Titanium Bone Lacing costs me 15 points of essence instead of 1.5. Again, changing the decimal point into a comma in the XML file fixes the problem.

**Comment by chummer5a** [comment]
Must be a localisation issue. I take it you're in a country that uses commas for decimals?

**Comment by tradloff** [comment]
That is correct.

**Comment by chummer5a** [comment]
That's what it's for, yeah. is it possible that your en-US culture has been changed to use commas as decimal separators?

**Comment by chummer5a** [comment]
if you're comfortable with testing and building the application, try changing lines 373-374 to
```
			_decPointsPerLevel = Convert.ToDecimal(objXmlPower["points"].InnerText, CultureInfo.InvariantCulture);
            _decAdeptWayDiscount = Convert.ToDecimal(objXmlPower["adeptway"].InnerText, CultureInfo.InvariantCulture);
```
and chuck this at the top:
`using System.Globalization;`

**Comment by tradloff** [comment]
My system locale entries are split up between en_US and de_DE. This one here seems to be the problem's cause: `LC_NUMERIC=de_DE.utf8` 

I'm running Linux, so I'd have a hard time building chummer. But if you can make a version with the proposed changes available to me, I'll be happy to test it.

**Comment by chummer5a** [comment]
[Debug.zip](https://github.com/chummer5a/chummer5a/files/212996/Debug.zip)

Give this a crack.

**Comment by tradloff** [comment]
Thanks. I can now add adept powers and 'ware without problems. But when I save and reopen the file I get this error: 

```
System.ArgumentOutOfRangeException: Value of '5' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.MetatypeSelected() in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 15095
   at Chummer.frmCreate.frmCreate_Load(Object sender, EventArgs e) in D:\Coding\chummer5a\Chummer\Character Creation\frmCreate.cs:line 557
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by joha4270** [comment]
Can you upload that file somewhere? , i would like to know what it uses as max/min

**Comment by tradloff** [comment]
Here you go: http://www98.zippyshare.com/v/HiENgXJ0/file.html

**Comment by joha4270** [comment]
That error seems to be related to some interaction between Essence loss and
the free level 6 magican. Not quite sure if it is the same error we are
seeing or just discovering another.

Can you try to make a character not a cyberadept and see if it persists?

**Comment by tradloff** [comment]
I can't seem to reproduce the exception anymore, not even with the file I gave you. At least I haven't had any problems with the locales anymore, which lets me assume the errors are unrelated.
