### ISSUE TITLE
Crash when adding Pilot Program (Drone)

### ISSUE THREAD

**Issue by fungasaurjr** [chummer5a/chummer5a#760]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.179.0

### Expected behaviour
Able to add Pilot Program (Drone) as Modifications to Drones

### Actual behaviour

When Pilot Program mod is selected system crashes with following message.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XPath.XPathException: Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.
   at MS.Internal.Xml.XPath.CompiledXpathExpr.get_QueryTree()
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr, XPathNodeIterator context)
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr)
   at Chummer.VehicleMod.get_TotalCost() in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 14542
   at Chummer.Vehicle.get_TotalCost() in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 15995
   at Chummer.frmCreate.RefreshSelectedVehicle() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 19780
   at Chummer.frmCreate.tsVehicleAddMod_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 9228
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.0.0
    Win32 Version: 5.179.0
    CodeBase: file:///C:/Users/Ken/Chummer/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

### Steps to reproduce the behaviour
Open .chum5 file
Add Vehicle (Drone) (Tested with Roto Drone and Liittle Buddy Drone)

Add Modification to Drone

Select Pilot Program (Drone)

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System
Windows 10
### Use of international language content
N/a
### Last known good version
Unkown
### Link to affected character file
Provided the file I was working on when discovered issue and a recreated file using the roto drone. 

https://drive.google.com/folderview?id=0B6pZ9Nhu5xk6QUpHYjg5aVJuN0k&usp=sharing

**Comment by chummer5a** [comment]
Again, no repro in 5.179.766; I was fiddling with that code the other day though, so you may be a couple of patches behind. Could you please test with the latest version and let me know how you go? Thanks for the in-depth issue report as well, it helps out a lot!

**Comment by fungasaurjr** [comment]
Closing as issue no longer exists in current build...5.179.769
