### ISSUE TITLE
Armor Defaulting to Equipped

### ISSUE THREAD

**Issue by fungasaurjr** [chummer5a/chummer5a#761]
##Required Fields
Please fill these out as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.179.0
### Expected behaviour
System to be stable when multiple types of armor for the same "slot" are equipped.

### Actual behaviour
System Crashes when .chum5 file with certain combinations of armor for are marked as equipped. Armor is marked as equipped on purchase.
Tested With:
File Dum Dum Test1 (No Issue)
Armored Clothing and
Armored Jacket 

File: Dum Dum Test2 (Issue)
Vashon Synergist Business Line and
Ares Wild Hunt

File Dum Dum Test3 (No Issues)
Ares Wild Hunt and
Armored Jacket

File: Dum Dum Test 4 (No Issue)
Ares Wild Hunt and
Urban Explorer Jump Suit

File Dum Dum Test 5 (Issue)
Ares Wild Hunt and
Mortimer of London Summit Dress

File Dum Dum Test 6 (No Issue)
Ares Wild Hunt and
Mortimer of London Summit Dress (Unchecked Equipped Box)

(Sorry cant do anymore test files tonight, but this may be isolated to Run and Gun Armor)

Been working on a character all weekend and kept running into this issue where I would make it all the way through Character Creation, then save and close the file only to have it crash on open, thought it was related to the drone issue previously reported but it seems there were two issues. 

### Steps to reproduce the behaviour
Open/Create Character
Add Armor 1 (Defaults to Equipped)
Add Armor 2 (Defaults to Equipped)
Save File
Close File
Open File

##Helpful Fields
Equipped Check Box
Workaround is to only have one piece of armor marked as equipped
Seems to be limited to Run and Gun Armor

### Operating System
Windows 10
### Use of international language content
N/a

### Last known good version
Unknown

### Link to affected character files
https://drive.google.com/folderview?id=0B6pZ9Nhu5xk6eUR2Qm55SVBORXM&usp=sharing

Error Message
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at Chummer.frmCreate.RefreshLimitModifiers() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 17831
   at Chummer.frmCreate.UpdateCharacterInfo() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 17362
   at Chummer.frmCreate.nudDEP_ValueChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 4534
   at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Chummer.frmCreate.InitializeComponent() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.Designer.cs:line 3874
   at Chummer.frmCreate..ctor(Character objCharacter) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 45
   at Chummer.frmMain.LoadCharacter(String strFileName, Boolean blnIncludeInMRU, String strNewName, Boolean blnClearFileName) in C:\projects\chummer5a\Chummer\frmMain.cs:line 666
   at Chummer.frmMain.mnuMRU_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\frmMain.cs:line 286
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.0.0
    Win32 Version: 5.179.0
    CodeBase: file:///C:/Users/Ken/Chummer/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by chummer5a** [comment]
Hrm, I can't reproduce it in 5.179.766 with any of your test characters. To be honest it looks like the code's chucking a hissy fit about your Depth rating, but there's no reason it should be doing that that I can see.

**Comment by fungasaurjr** [comment]
Crap sorry, i thought i was running most up to date version... Im new to all of this... Where is the best spot to get the most up to date build.
Does that mean that all the files opened for you?

**Comment by chummer5a** [comment]
https://github.com/chummer5a/chummer5a/releases 

Files all opened fine for me, yes.

**Comment by fungasaurjr** [comment]
Many thanks will give a check tomorrow.

**Comment by fungasaurjr** [comment]
Closing as issue no longer exists in current build...5.179.769
