### ISSUE TITLE
Modifying stats on drones creates an exception.

### ISSUE THREAD

**Issue by skarsol** [chummer5a/chummer5a#780]
### Chummer Version
5.179.769 and .775

### Expected behaviour
Adding Handling (Drone) Rating 5 to a Handling 4 drone should make it Handling 5.
It shouldn't throw an error.
### Actual behaviour
It adds the Rating to the current value. (Handling becomes 9)
It throws an error.
Unhandled exception: Input string was not in a correct format.
### Steps to reproduce the behaviour
Add a drone.
Add a modification.
Select any base stat (eg: Handling (Drone))
Select any rating.
Hit OK

**Comment by Blackbaud-SeanLong** [comment]
Duplicated on a DEBUG build, 5.179.781.

Same error. Exception text follows:

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at Chummer.VehicleMod.get_CalculatedSlots() in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 13623
   at Chummer.Vehicle.get_SlotsUsed() in C:\projects\chummer5a\Chummer\Classes\clsEquipment.cs:line 14954
   at Chummer.frmCreate.RefreshSelectedVehicle() in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 19351
   at Chummer.frmCreate.tsVehicleAddMod_Click(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmCreate.cs:line 9108
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SquadronROE** [comment]
Using my private account instead of my work one. Sorry about that.

Looks like this also occurs for Body, but in TotalBody (still in the Convert.ToInt32 method).

**Comment by SquadronROE** [comment]
Stats will cause the exception in different methods, but always with the Convert.ToInt32 method. I think something's up in how the vehicle's stats are being stored.

**Comment by SquadronROE** [comment]
So I think I figured out a fix for this, but I'm not sure if it will break existing functionality. Looking into that now. If anyone more experienced in this project looks at this, I'm taking a look at the CalculatedSlots function, which returns an int value.

It looks like the formatting for the drone modifications input isn't what is expected. Instead of it just being "Rating", it's "Handling - Rating - 1". This means that it is only replacing one part of the string before it tries to convert the entire thing to Int32. Hence the exception.

I'm debating a couple of approaches here, depending on where else this CalculatedSlots function is referenced and what inputs it can take.

1. Add a try > catch for the function that looks for the above situation and appropriately handles it (just using _intRating?)
2. It looks like _intRating IS the rating (ie 1, 2, etc). Why not just use that? It's already an Int?
3. Branch the entire CalculatedSlots function to let us handle modifications to drones differently than other things that may use CalculatedSlots?
4. Figure out what is sending that different Ratings string, and sanitize that before sending it to CalcuatedSlots.

**Comment by SquadronROE** [comment]
OK, so I took a little of 2 and a little of 1 and just made an else if for the "Handling" input. At line 13621 in clsEquipment.cs I added:

		else if (_strSlots.Contains("- Rating -"))
                {
                    return Convert.ToInt32(_intRating);
                }
                else

It seems silly to me to basically replace a "Rating" string with a converted integer (unnecessary conversion to string then back to Int?), but I could certainly be missing something. In my local environment this resolved the issue.

I'm going to make the change in my fork and do some further testing to try to verify that this doesn't break existing functionality, but it shouldn't since it's an else if that only fires when the Drone modification is selected.

**Comment by chummer5a** [comment]
It's supposed to represent the consumption of mod points, from what I can see. The mod slots that would be consumed are equal to Handling - Rating - 1, with the minimum Rating being equal to the Handling + 1. CalculatedSlots just needs to know how to handle that as an expression. I'd suggest looking at the OwnCost property just above it, which uses string replacement and XPathExpression to convert it into an equation then into an int.

**Comment by SquadronROE** [comment]
Got it, I'll give that a shot and take a look at the rules again. But at
least it doesn't crash!

**Comment by skarsol** [comment]
I've fixed this in my patch to enable tracking of mod points for vehicles and drones. The code as is wasn't going to work without a lot of shoehorning because at the point where the slots are calculated, the mod doesn't know the base stats of the vehicle it's modifying and thus can't calculate how many mod slots it should use. Your quick fix to just return _intRating means that Acceleration (Drone) (Rating 2) will always register as 2 slots, so much easier to adjust the XML to just be "Rating" instead of "Handling - Rating - 1".

**Comment by SquadronROE** [comment]
Yep, that makes perfect sense. I was thinking about that, actually, and the
amount of work it would take to really fix it at the code level (lots of
paths to adjust). Plus I hadn't found the XML it pulls that from yet.
That's the much better fix.I just have haven't had the time to work on this
anymore.

Thanks for grabbing it, good work!

**Comment by skarsol** [comment]
Created a pull request that addresses this (among other things).

**Comment by skarsol** [comment]
Fixed.
